environment:
  run: environment/start

relaax-metrics-server:
  enable_unknown_metrics: true
  metrics:
    episode_reward: true
    server_latency: true
    action: true
    mu: false
    sigma2: false
    critic: true

  bind: localhost:7002
  metrics_dir: logs/metrics
  log_metrics_to_console: false
  log_level: INFO

relaax-metrics-server:
  bind: localhost:7002
  metrics-dir: logs/da3c/metrics
  log_metrics: false
  log_level: DEBUG

relaax-parameter-server:
  bind: localhost:7000
  checkpoint-dir: logs/da3c/checkpoints
  checkpoint_time_interval: 3600
  checkpoints_to_keep: 24
  log-level: DEBUG

relaax-rlx-server:
  bind: localhost:7001
  log_level: DEBUG

relaax-wsproxy:
  bind: localhost:9000
  log_level: DEBUG

version: 1.1.0
algorithm:
  name: da3c

  input:
    shape: [58]
    history: 1
    use_convolutions: false

  output:
    continuous: true
    action_size: 2                # action size for the given environment
    action_high: 1.0              # upper boundary for clipping continuous action
    action_low: -1.0              # lower boundary for clipping continuous action

  hidden_sizes: [300,300,300]
  batch_size: 200                  # local loop size for one episode

  use_lstm: true                  # to use LSTM instead of FF, set to the True
  max_global_step: 1e8            # amount of maximum global steps to pass through the training

  actor_initial_learning_rate: 0.0002
  critic_initial_learning_rate: 0.002
  entropy_beta: 0.01              # entropy regularization constant
  rewards_gamma: 0.99             # rewards discount factor
  optimizer: RMSProp

  RMSProp:
    decay: 0.99
    epsilon: 0.1
  gradients_norm_clipping: 50.0
