environment:
  run: python environment/training.py
  name: BipedalWalker-v2
  shape: [24]
  infinite_run: True

relaax-metrics-server:
  enable_unknown_metrics: false
  metrics:
    episode_reward: true
    server_latency: false
    action: false
    mu: false
    sigma2: false
    critic: true

  bind: localhost:7002
  metrics_dir: logs/metrics
  log_metrics_to_console: false
  log_level: INFO

relaax-parameter-server:
  bind: localhost:7000
  checkpoint-dir: logs/checkpoints
  log-level: INFO

relaax-rlx-server:
  bind: localhost:7001
  log-level: INFO

version: 1.1.0
algorithm:
  name: da3c                      # short name for algorithm to load

  input:
    shape: [24]                   # shape of input state
    history: 1                    # number of consecutive states to stuck to represent an input
    use_convolutions: false       # set to True to use convolutions to process the input,
                                  # it uses the set of convolutions from universe architecture by default
  output:
    continuous: true              # set to true to switch to continuous action space
    action_size: 4                # action size for the given environment

  batch_size: 100                 # maximum batch size, which need to accumulate for one update
  hidden_sizes: [200, 128]        # list of num_units for hidden fc layers

  use_lstm: true                  # to use LSTM instead of FF, set to the True
  max_global_step: 5e6            # amount of maximum global steps to pass through the training

  rewards_gamma: 0.99             # rewards discount factor
  use_filter: True                # set to True to use mean/std running filter

  initial_learning_rate: 2e-4     # initial learning rate to start the training
  use_linear_schedule: true       # set to True to use linear learning rate annealing wrt max_global_step
  critic_scale: 10.0              # coefficient to scale the critic loss or learning rate

  entropy_beta: 1e-4              # entropy regularization constant
  entropy_type: Origin            # switch between relevant entropy types: Origin | Gauss

  optimizer: RMSProp
  gradients_norm_clipping: 40.0   # value to clip the gradients by its global norm, set to false to not

  RMSProp:                        # RMSProp optimizer specific parameters
    decay: 0.99
    epsilon: 0.1
