environment:
  run: python environment/training.py
  steps: 3000
  max_episodes: 1
  infinite_run: false

relaax-parameter-server:
  --bind: localhost:7000
  --checkpoint-dir: logs/checkpoints
  --log-level: DEBUG
  --metrics-dir: logs/metrics

relaax-rlx-server:
  --bind: localhost:7001
  --log-level: DEBUG

algorithm:
  name: da3c                      # short name for algorithm to load

  input:
    shape: [41]                   # shape of input state
    history: 1                    # number of consecutive states to stack
    use_convolutions: false       # set to true to process input by convolution layers

  output:
    continuous: true              # set to true to switch to continuous action space
    action_size: 18               # action size for the given environment
    action_high: []
    action_low: []
    scale: 1.0                    # multiplier to scale continuous output

  hidden_sizes: [41,41]
  batch_size: 5                   # maximum batch size, which need to accumulate for one update

  use_icm: false                  # to use ICM, set to the True
  use_lstm: false                 # to use LSTM instead of FF, set to the True
  max_global_step: 30000          # amount of maximum global steps to pass through the training

  entropy_beta: 0.01              # entropy regularization constant
  rewards_gamma: 0.99             # rewards discount factor
  use_gae: false                  # switcher for generalized advantage estimation
  gae_lambda: 1.0                 # lambda for generalized advantage estimation

  initial_learning_rate: 0.02     # initial learning rate, which can be anneal by some procedure
  gradients_norm_clipping: false  # gradients clipping by global norm, if false then it is ignored
  optimizer: Adam                 # name of optimizer to use within training

  RMSProp:                        # RMSProp optimizer specific parameters
    decay: 0.99
    epsilon: 0.1

  ICM:                            # ICM specific parameters
    alpha: 0.1
    beta: 0.2
