environment:
  run: python environment/training.py
  steps: 200
  infinite_run: True

relaax-metrics-server:
  enable_unknown_metrics: false
  metrics:
    episode_reward: true
    server_latency: false
    action: false
    mu: false
    sigma2: false
    critic: true

  bind: localhost:7002
  metrics_dir: logs/metrics
  log_metrics_to_console: false
  log_level: INFO

relaax-parameter-server:
  --bind: localhost:7000
  --checkpoint-dir: logs/checkpoints
  --log-level: INFO

relaax-rlx-server:
  --bind: localhost:7001
  --log-level: INFO

algorithm:
  name: da3c

  input:
    shape: [41]                   # shape of input state
    history: 1                    # number of consecutive states to stack
    use_convolutions: false       # set to true to process input by convolution layers

  output:
    continuous: true              # set to true to switch to continuous action space
    action_size: 18               # action size for the given environment

  batch_size: 100                 # local loop size for one episode
  hidden_sizes: [200, 128]
  critic_scale: 0.25

  use_icm: false                  # ICM module switcher
  gae_lambda: 1.00                # lambda for generalized advantage estimation

  use_lstm: true                  # to use LSTM instead of FF, set to the True
  max_global_step: 1e7            # amount of maximum global steps to pass through the training

  initial_learning_rate: 8e-4

  entropy_beta: 1e-4              # entropy regularization constant
  rewards_gamma: 0.99             # rewards discount factor
  gradients_norm_clipping: 40.
  use_filter: True

  optimizer: RMSProp
  RMSProp:                        # RMSProp optimizer specific parameters
    decay: 0.99
    epsilon: 0.1
