environment:
  run: python environment/training.py
  name: BoxingDeterministic-v4
  shape: [84, 84]                 # [height, width] or [height, width, channels] of env's input
  infinite_run: True

relaax-metrics-server:
  enable_unknown_metrics: true
  metrics:
    episode_reward: true
    server_latency: false
    action: false
    critic: true
    state: false

  bind: localhost:7002
  metrics_dir: logs/metrics
  log_metrics_to_console: false
  log_level: INFO  # DEBUG | INFO

relaax-parameter-server:
  bind: localhost:7000
  checkpoint-dir: logs/checkpoints
  log-level: INFO  # DEBUG | INFO

relaax-rlx-server:
  bind: localhost:7001
  log-level: INFO  # DEBUG | INFO

version: 1.1.0
algorithm:
  name: da3c

  input:
    shape: [84, 84]               # state: [height, width] or [height, width, channels]
    history: 4                    # number of consecutive states to stuck to represent an input
    use_convolutions: true        # set to True to use convolutions to process the input,
                                  # it uses the set of convolutions from universe architecture by default
    universe: false               # set to False to use classic set of A3C convolutions

  output:
    continuous: false             # set to True to handle with continuous action type
    action_size: 18               # action size for the given environment

  hidden_sizes: [256]             # list of num_units for hidden fc layers
  batch_size: 5                   # experience size for one update

  use_lstm: false                 # to use LSTM instead of FF, set to the True
  max_global_step: 1e8            # amount of maximum global steps to pass through the training

  rewards_gamma: 0.99             # rewards discount factor

  initial_learning_rate: 7e-4     # initial learning rate to start the training
  use_linear_schedule: false      # set to True to use linear learning rate annealing wrt max_global_step

  optimizer: RMSProp              # type of optimizer to use: Adam | RMSProp
  gradients_norm_clipping: 40.    # value to clip the gradients by its global norm

  RMSProp:                        # RMSProp optimizer specific parameters
    decay: 0.99
    epsilon: 0.1
