environment:
  run: python environment/training.py
  name: BoxingDeterministic-v4
  shape: [42, 42]
  no_op_max: 30
  stochastic_reset: True
  infinite_run: True

relaax-metrics-server:
  enable_unknown_metrics: true
  metrics:
    episode_reward: true
    server_latency: false
    action: true
    critic: true
    state: false

  bind: localhost:7002
  metrics_dir: logs/metrics
  log_metrics_to_console: false
  log_level: INFO  # DEBUG | INFO

relaax-parameter-server:
  bind: localhost:7000
  checkpoint-dir: logs/checkpoints
  checkpoint_step_interval: 2000000
  checkpoints_to_keep: 2
  best_checkpoints_to_keep: 4
  log-level: INFO

relaax-rlx-server:
  bind: localhost:7001
  log-level: INFO

version: 1.1.0
algorithm:
  name: da3c

  input:
    shape: [42, 42]
    history: 4
    use_convolutions: true

  output:
    continuous: false
    action_size: 18               # action size for the given environment

  batch_size: 5                   # local loop size for one episode
  hidden_sizes: [256]

  use_lstm: false                 # to use LSTM instead of FF, set to the True
  max_global_step: 5e7            # amount of maximum global steps to pass through the training

  optimizer: Adam
  initial_learning_rate: 1e-4

  entropy_beta: 0.01              # entropy regularization constant
  rewards_gamma: 0.99             # rewards discount factor
  gae_lambda: 0.97                # lambda for generalized advantage estimation
  gradients_norm_clipping: 40.

  combine_gradient: dc            # dc | fifo | average
  dc_lambda: 0.05
